//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModels
{
    using System;
    
    public partial class Document
    {
        public System.Guid DocumentID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.DateTime> LastAccessedDate { get; set; }
        public string UploadUserId { get; set; }
        public Nullable<int> DocumentSize { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DocumentName { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
