export const LOAD_DOCUMENTS_SUCCESS = "LOAD_DOCUMENTS_SUCCESS";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const DOWNLOAD_BATCH_FILES_SUCCESS = "DOWNLOAD_BATCH_FILES_SUCCESS";
export const UPLOAD_DOCUMENT_FAIL = "UPLOAD_DOCUMENT_FAIL";
export const Sign_In_SUCCESS = "Sign_In_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const DOWNLOAD_DOCUMENT_FAIL = "DOWNLOAD_DOCUMENT_FAIL";
export const LOAD_DOCUMENT_FAIL = "LOAD_DOCUMENT_FAIL";


